#!/usr/bin/env python
"""
This script is used to launch ec2 salt minions
"""

import os
import shaker


def main():
    """
    The main function
    """
    cli, config_dir, profile = shaker.cli.parse_cli()
    s = shaker.ebs.EBSFactory(cli, config_dir, profile)
    s.process()

if __name__ == '__main__':
    main()
